# Part of the Oxygen Health Systems Odoo customizations.
#
# Purchase counterpart of odoo/addons/sale/controllers/product_configurator.py.
# It is a standalone controller (not a subclass of the sale one) on purpose:
# subclassing an Odoo controller replaces it for *all* its routes, which would
# make the sales configurator use vendor prices too.

from datetime import datetime

from odoo.http import Controller, request, route


class PurchaseProductConfiguratorController(Controller):

    @route(
        route='/purchase/product_configurator/get_values',
        type='jsonrpc',
        auth='user',
        readonly=True,
    )
    def purchase_product_configurator_get_values(
        self,
        product_template_id,
        quantity,
        so_date,
        currency_id=None,
        product_uom_id=None,
        company_id=None,
        partner_id=None,
        ptav_ids=None,
        only_main_product=False,
        **kwargs,
    ):
        """Return all product information needed for the purchase product configurator.

        :param int product_template_id: The product for which to seek information, as a
            `product.template` id.
        :param int quantity: The quantity of the product.
        :param str so_date: The date of the `purchase.order`, to compute the price at the right
            rate (ISO format).
        :param int|None currency_id: The currency of the order, as a `res.currency` id.
        :param int|None product_uom_id: The unit of measure of the product, as a `uom.uom` id.
        :param int|None company_id: The company to use, as a `res.company` id.
        :param int|None partner_id: The vendor of the order, as a `res.partner` id.
        :param list(int)|None ptav_ids: The combination of the product, as a list of
            `product.template.attribute.value` ids.
        :param bool only_main_product: Whether the optional products should be included or not.
        :param dict kwargs: Locally unused data passed to `_get_product_information`.
        :rtype: dict
        :return: A dict containing a list of products and a list of optional products information,
            generated by :meth:`_get_product_information`.
        """
        if company_id:
            request.update_context(allowed_company_ids=[company_id])
        product_template = self._get_product_template(product_template_id)

        combination = request.env['product.template.attribute.value']
        if ptav_ids:
            combination = request.env['product.template.attribute.value'].browse(ptav_ids).filtered(
                lambda ptav: ptav.product_tmpl_id.id == product_template_id
            )
            # Set missing attributes (unsaved no_variant attributes, or new attribute on existing
            # product)
            unconfigured_ptals = (
                product_template.attribute_line_ids - combination.attribute_line_id
            ).filtered(lambda ptal: ptal.attribute_id.display_type != 'multi')
            combination += unconfigured_ptals.mapped(
                lambda ptal: ptal.product_template_value_ids._only_active()[:1]
            )
        if not combination:
            combination = product_template._get_first_possible_combination()
        currency = self._get_currency(currency_id)
        partner = request.env['res.partner'].browse(partner_id)
        date = datetime.fromisoformat(so_date)

        return {
            'products': [
                dict(
                    **self._get_product_information(
                        product_template,
                        combination,
                        currency,
                        partner,
                        date,
                        quantity=quantity,
                        product_uom_id=product_uom_id,
                        **kwargs,
                    ),
                )
            ],
            'optional_products': [
                dict(
                    **self._get_product_information(
                        optional_product_template,
                        optional_product_template._get_first_possible_combination(
                            parent_combination=combination
                        ),
                        currency,
                        partner,
                        date,
                        # giving all the ptav of the parent product to get all the exclusions
                        parent_combination=product_template.attribute_line_ids.\
                            product_template_value_ids,
                        **kwargs,
                    ),
                    parent_product_tmpl_id=product_template.id,
                ) for optional_product_template in product_template._get_purchase_optional_products()
                if self._should_show_product(optional_product_template, combination)
            ] if not only_main_product else [],
            'currency_id': currency.id,
        }

    @route(
        route='/purchase/product_configurator/create_product',
        type='jsonrpc',
        auth='user',
        methods=['POST'],
    )
    def purchase_product_configurator_create_product(self, product_template_id, ptav_ids):
        """Create the product when there is a dynamic attribute in the combination.

        :param int product_template_id: The product for which to seek information, as a
            `product.template` id.
        :param list(int) ptav_ids: The combination of the product, as a list of
            `product.template.attribute.value` ids.
        :rtype: int
        :return: The product created, as a `product.product` id.
        """
        product_template = self._get_product_template(product_template_id)
        combination = request.env['product.template.attribute.value'].browse(ptav_ids)
        product = product_template._create_product_variant(combination)
        return product.id

    @route(
        route='/purchase/product_configurator/update_combination',
        type='jsonrpc',
        auth='user',
        methods=['POST'],
        readonly=True,
    )
    def purchase_product_configurator_update_combination(
        self,
        product_template_id,
        ptav_ids,
        so_date,
        quantity,
        currency_id=None,
        product_uom_id=None,
        company_id=None,
        partner_id=None,
        **kwargs,
    ):
        """Return the updated combination information (name, id, vendor price).

        :param int product_template_id: The product for which to seek information, as a
            `product.template` id.
        :param list(int) ptav_ids: The combination of the product, as a list of
            `product.template.attribute.value` ids.
        :param str so_date: The date of the `purchase.order`, to compute the price at the right
            rate (ISO format).
        :param int quantity: The quantity of the product.
        :param int|None currency_id: The currency of the order, as a `res.currency` id.
        :param int|None product_uom_id: The unit of measure of the product, as a `uom.uom` id.
        :param int|None company_id: The company to use, as a `res.company` id.
        :param int|None partner_id: The vendor of the order, as a `res.partner` id.
        :param dict kwargs: Locally unused data passed to `_get_basic_product_information`.
        :rtype: dict
        :return: Basic information about a product, generated by
            :meth:`_get_basic_product_information`.
        """
        if company_id:
            request.update_context(allowed_company_ids=[company_id])
        product_template = self._get_product_template(product_template_id)
        product_uom = request.env['uom.uom'].browse(product_uom_id) or product_template.uom_id
        currency = self._get_currency(currency_id)
        partner = request.env['res.partner'].browse(partner_id)
        combination = request.env['product.template.attribute.value'].browse(ptav_ids)
        product = product_template._get_variant_for_combination(combination)

        return self._get_basic_product_information(
            product or product_template,
            combination,
            quantity=quantity or 0.0,
            uom=product_uom,
            currency=currency,
            date=datetime.fromisoformat(so_date),
            partner=partner,
            **kwargs,
        )

    @route(
        route='/purchase/product_configurator/get_optional_products',
        type='jsonrpc',
        auth='user',
        readonly=True,
    )
    def purchase_product_configurator_get_optional_products(
        self,
        product_template_id,
        ptav_ids,
        parent_ptav_ids,
        so_date,
        currency_id=None,
        company_id=None,
        partner_id=None,
        **kwargs,
    ):
        """Return information about the purchasable optional products of the given template.

        :param int product_template_id: The product for which to seek information, as a
            `product.template` id.
        :param list(int) ptav_ids: The combination of the product, as a list of
            `product.template.attribute.value` ids.
        :param list(int) parent_ptav_ids: The combination of the parent product, as a list of
            `product.template.attribute.value` ids.
        :param str so_date: The date of the `purchase.order`, to compute the price at the right
            rate (ISO format).
        :param int|None currency_id: The currency of the order, as a `res.currency` id.
        :param int|None company_id: The company to use, as a `res.company` id.
        :param int|None partner_id: The vendor of the order, as a `res.partner` id.
        :param dict kwargs: Locally unused data passed to `_get_product_information`.
        :rtype: [dict]
        :return: A list of optional products information, generated by
            :meth:`_get_product_information`.
        """
        if company_id:
            request.update_context(allowed_company_ids=[company_id])
        product_template = self._get_product_template(product_template_id)
        parent_combination = request.env['product.template.attribute.value'].browse(
            parent_ptav_ids + ptav_ids
        )
        currency = self._get_currency(currency_id)
        partner = request.env['res.partner'].browse(partner_id)
        return [
            dict(
                **self._get_product_information(
                    optional_product_template,
                    optional_product_template._get_first_possible_combination(
                        parent_combination=parent_combination
                    ),
                    currency,
                    partner,
                    datetime.fromisoformat(so_date),
                    parent_combination=parent_combination,
                    **kwargs,
                ),
                parent_product_tmpl_id=product_template.id,
            ) for optional_product_template in product_template._get_purchase_optional_products()
            if self._should_show_product(optional_product_template, parent_combination)
        ]

    # -------------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------------

    def _get_product_template(self, product_template_id):
        return request.env['product.template'].browse(product_template_id)

    def _get_currency(self, currency_id):
        return (
            (currency_id and request.env['res.currency'].browse(currency_id))
            or request.env.company.currency_id
        )

    def _get_product_information(
        self,
        product_template,
        combination,
        currency,
        partner,
        date,
        quantity=1,
        product_uom_id=None,
        parent_combination=None,
        show_packaging=True,
        **kwargs,
    ):
        """Return complete information about a product.

        Same structure as the sale configurator (see
        `sale.controllers.product_configurator`), so that the sale configurator
        components can be reused as-is.

        :param product.template product_template: The product for which to seek information.
        :param product.template.attribute.value combination: The combination of the product.
        :param res.currency currency: The currency of the order.
        :param res.partner partner: The vendor of the order.
        :param datetime date: The date of the order, to compute the price at the right rate.
        :param int quantity: The quantity of the product.
        :param int|None product_uom_id: The unit of measure of the product, as a `uom.uom` id.
        :param product.template.attribute.value|None parent_combination: The combination of the
            parent product.
        :param bool show_packaging: Whether the available units of measure should be returned.
        :param dict kwargs: Locally unused data passed to `_get_basic_product_information`.
        :rtype: dict
        """
        uom = (
            (product_uom_id and request.env['uom.uom'].browse(product_uom_id))
            or product_template.uom_id
        )
        product = product_template._get_variant_for_combination(combination)
        attribute_exclusions = product_template._get_attribute_exclusions(
            parent_combination=parent_combination,
            combination_ids=combination.ids,
        )
        product_or_template = product or product_template
        ptals = product_template.attribute_line_ids
        attrs_map = {
            attr_data['id']: attr_data
            for attr_data in ptals.attribute_id.read(['id', 'name', 'display_type'])
        }
        ptavs = ptals.product_template_value_ids.filtered(
            lambda p: p.ptav_active or combination and p.id in combination.ids
        )
        ptavs_map = dict(zip(ptavs.ids, ptavs.read(['name', 'html_color', 'image', 'is_custom'])))

        values = dict(
            product_tmpl_id=product_template.id,
            **self._get_basic_product_information(
                product_or_template,
                combination,
                quantity=quantity,
                uom=uom,
                currency=currency,
                date=date,
                partner=partner,
                **kwargs,
            ),
            quantity=quantity,
            uom=uom.read(['id', 'display_name'])[0],
            attribute_lines=[{
                'id': ptal.id,
                'attribute': dict(**attrs_map[ptal.attribute_id.id]),
                'attribute_values': [
                    dict(
                        **ptavs_map[ptav.id],
                        price_extra=self._get_ptav_price_extra(
                            ptav, currency, date, product_or_template
                        ),
                    ) for ptav in ptal.product_template_value_ids
                    if ptav.ptav_active or (combination and ptav.id in combination.ids)
                ],
                'selected_attribute_value_ids': combination.filtered(
                    lambda c: ptal in c.attribute_line_id
                ).ids,
                'create_variant': ptal.attribute_id.create_variant,
            } for ptal in product_template.attribute_line_ids],
            exclusions=attribute_exclusions['exclusions'],
            archived_combinations=attribute_exclusions['archived_combinations'],
            parent_exclusions=attribute_exclusions['parent_exclusions'],
        )
        if show_packaging and product_template._has_multiple_uoms():
            values['available_uoms'] = product_template._get_available_uoms().read(
                ['id', 'display_name']
            )
        return values

    def _get_basic_product_information(
        self,
        product_or_template,
        combination,
        quantity=1.0,
        uom=None,
        currency=None,
        date=None,
        partner=None,
        **kwargs,
    ):
        """Return basic information about a product.

        :param product.product|product.template product_or_template: The product for which to seek
            information.
        :param product.template.attribute.value combination: The combination of the product.
        :param float quantity: The quantity of the product.
        :param uom.uom|None uom: The unit of measure of the product.
        :param res.currency currency: The currency of the order.
        :param datetime date: The date of the order.
        :param res.partner partner: The vendor of the order.
        :param dict kwargs: Unused (e.g. `pricelist_id` sent by the generic configurator dialog).
        :rtype: dict
        :return: A dict with the following structure:
            {
                'id': int|False,  # `product.product` id, False for a template.
                'description_sale': str|False,  # purchase description, under the key expected
                                                # by the sale configurator components.
                'display_name': str,
                'price': float,  # vendor price (or cost) in the order currency
                'show_extra_price': bool,
            }
        """
        basic_information = product_or_template.read(['description_purchase', 'display_name'])[0]
        basic_information['description_sale'] = basic_information.pop('description_purchase')
        # If the product is a template, check the combination to compute the name to take dynamic
        # and no_variant attributes into account. Also, drop the id which was auto-included by the
        # search but isn't relevant since it is supposed to be the id of a `product.product` record.
        if not product_or_template.is_product_variant:
            basic_information['id'] = False
            combination_name = combination._get_combination_name()
            if combination_name:
                basic_information.update(
                    display_name=f"{basic_information['display_name']} ({combination_name})"
                )
        price = self._get_purchase_price(
            product_or_template,
            quantity=quantity,
            uom=uom,
            currency=currency,
            date=date,
            partner=partner,
        )
        return dict(
            **basic_information,
            price=price,
            # Attribute "extra prices" are a sales concept: never show them on purchases.
            show_extra_price=False,
        )

    def _get_purchase_price(self, product_or_template, quantity, uom, currency, date, partner):
        """Return the unit price to display in the purchase configurator.

        The vendor price (`product.supplierinfo`) of the given vendor is used when there is
        one for the product, quantity and date, like on a purchase order line; otherwise the
        product cost is used.

        :param product.product|product.template product_or_template: The product.
        :param float quantity: The quantity of the product.
        :param uom.uom|None uom: The unit of measure of the order line.
        :param res.currency currency: The currency of the order.
        :param datetime|date date: The date of the order.
        :param res.partner partner: The vendor of the order.
        :rtype: float
        """
        company = request.env.company
        uom = uom or product_or_template.uom_id
        date = date.date() if isinstance(date, datetime) else date
        product = (
            product_or_template
            if product_or_template.is_product_variant
            else product_or_template.product_variant_id
        )

        seller = request.env['product.supplierinfo']
        if product:
            seller = product.with_company(company)._select_seller(
                partner_id=partner,
                quantity=quantity or 1.0,
                date=date,
                uom_id=uom,
                params={'force_uom': True},
            )

        if seller:
            price = seller.price
            if seller.currency_id != currency:
                price = seller.currency_id._convert(price, currency, company, date, round=False)
            seller_uom = seller.product_uom_id or product_or_template.uom_id
            if seller_uom != uom:
                price = seller_uom._compute_price(price, uom)
        else:
            price = product_or_template.standard_price
            cost_currency = product_or_template.cost_currency_id
            if cost_currency != currency:
                price = cost_currency._convert(price, currency, company, date, round=False)
            if product_or_template.uom_id != uom:
                price = product_or_template.uom_id._compute_price(price, uom)
        return currency.round(price)

    def _get_ptav_price_extra(self, ptav, currency, date, product_or_template):
        """Attribute value extra prices are sales prices: they are not relevant for purchases."""
        return 0.0

    def _should_show_product(self, product_template, parent_combination):
        """Decide whether an optional product should be shown in the configurator.

        :param product.template product_template: The product being checked.
        :param product.template.attribute.value parent_combination: The combination of the parent
            product.
        :rtype: bool
        """
        return True
